package io.github.gohoski.numai.model;

import android.content.Context;
import java.util.ArrayList;
import java.util.List;

import cc.nnproject.json.JSONArray;
import cc.nnproject.json.JSONObject;
import io.github.gohoski.numai.ui.MarkdownParser;

public class Message {
    private Role role = Role.USER;
    private String content = "";
    private String llm;
    private List<String> inputImages;
    private String outputImage;
    private boolean isError = false;
    private JSONArray toolCalls;
    private String toolCallId;
    private int searchResultCount = -1;

    // Unified cache fields
    private transient String cachedRawContent = null;
    private transient CharSequence cachedParsedDisplayContent = null;
    private transient CharSequence cachedParsedThinkContent = null;
    private transient String cachedThinkingRaw = null;
    private transient String cachedDisplayRaw = null;

    public Message(Role role, String content) {
        this.role = role;
        this.content = content != null ? content : "";
    }
    public Message(Role role, String content, String llm) {
        this.role = role;
        this.content = content != null ? content : "";
        this.llm = llm;
    }
    public Message(Role role, String content, List<String> inputImages, String llm) {
        this.role = role;
        this.content = content != null ? content : "";
        this.llm = llm;
        this.inputImages = inputImages;
    }

    public String getRole() {
        return role.toString();
    }

    public Role getRoleEnum() {
        return role;
    }

    public String getContent() {
        return content;
    }

    public String getLlm() {
        return llm;
    }

    public List<String> getInputImages() {
        return inputImages;
    }

    /** Filename of an image generated by an assistant, if this message has one. */
    public String getOutputImage() {
        return outputImage;
    }

    public void setOutputImage(String outputImage) {
        this.outputImage = outputImage;
    }

    public JSONArray getToolCalls() {
        return toolCalls;
    }

    public void setToolCalls(JSONArray toolCalls) {
        this.toolCalls = toolCalls;
    }

    public String getToolCallId() {
        return toolCallId;
    }

    public void setToolCallId(String toolCallId) {
        this.toolCallId = toolCallId;
    }

    public int getSearchResultCount() {
        return searchResultCount;
    }

    public void setSearchResultCount(int searchResultCount) {
        this.searchResultCount = searchResultCount;
    }

    public void updateContent(String additionalContent) {
        if (additionalContent != null && additionalContent.length() > 0) {
            this.content += additionalContent;
            invalidateCache();
        }
    }

    public void setContent(String newContent) {
        String safeContent = newContent != null ? newContent : "";
        if (!safeContent.equals(this.content)) {
            this.content = safeContent;
            invalidateCache();
        }
    }

    public void invalidateCache() {
        cachedRawContent = null;
        cachedParsedDisplayContent = null;
        cachedParsedThinkContent = null;
        cachedThinkingRaw = null;
        cachedDisplayRaw = null;
    }

    public String getThinkingRaw() {
        ensureParsedStructure();
        return cachedThinkingRaw;
    }

    public String getDisplayRaw() {
        ensureParsedStructure();
        return cachedDisplayRaw;
    }

    public CharSequence getParsedDisplayContent(Context context, boolean isGenerating) {
        ensureParsedStructure();
        if (cachedParsedDisplayContent == null) {
            cachedParsedDisplayContent = MarkdownParser.parse(context, cachedDisplayRaw, isGenerating);
        }
        return cachedParsedDisplayContent;
    }

    public CharSequence getParsedThinkContent(Context context, boolean isGenerating) {
        ensureParsedStructure();
        if (cachedParsedThinkContent == null) {
            cachedParsedThinkContent = MarkdownParser.parse(context, cachedThinkingRaw, isGenerating);
        }
        return cachedParsedThinkContent;
    }

    private void ensureParsedStructure() {
        if (cachedRawContent != null && cachedRawContent.equals(content)) {
            return;
        }

        cachedRawContent = content;
        cachedThinkingRaw = "";
        cachedDisplayRaw = "";

        if (content == null || content.length() == 0) {
            return;
        }

        String text = content;
        StringBuilder thinkSb = new StringBuilder();
        StringBuilder displaySb = new StringBuilder();
        int cursor = 0;

        while (cursor < text.length()) {
            int thinkStart = text.indexOf("<think>", cursor);
            if (thinkStart == -1) {
                displaySb.append(text.substring(cursor));
                break;
            }
            displaySb.append(text.substring(cursor, thinkStart));
            int thinkEnd = text.indexOf("</think>", thinkStart + 7);
            if (thinkEnd == -1) {
                if (thinkSb.length() > 0) thinkSb.append("\n\n");
                thinkSb.append(text.substring(thinkStart + 7));
                cursor = text.length();
                break;
            } else {
                if (thinkSb.length() > 0) thinkSb.append("\n\n");
                thinkSb.append(text.substring(thinkStart + 7, thinkEnd));
                cursor = thinkEnd + 8;
            }
        }

        cachedThinkingRaw = thinkSb.toString().trim();
        cachedDisplayRaw = stripThoughtChannelPrefix(displaySb.toString());
    }

    private static String stripThoughtChannelPrefix(String text) {
        if (text == null || text.length() == 0) return "";
        String trimmed = text.trim();
        String lower = trimmed.toLowerCase();

        if (lower.startsWith("thought") && lower.contains("channel")) {
            int idx = trimmed.indexOf('>');
            if (idx != -1 && idx < 30) {
                return trimmed.substring(idx + 1).trim();
            }
        }
        if (lower.startsWith("<|channel|>")) {
            return trimmed.substring(11).trim();
        }
        if (lower.startsWith("<channel>")) {
            return trimmed.substring(9).trim();
        }
        if (lower.startsWith("thought\n")) {
            return trimmed.substring(8).trim();
        }
        if (lower.startsWith("thought\r\n")) {
            return trimmed.substring(9).trim();
        }
        return trimmed;
    }

    public boolean isSent() {
        return role == Role.USER;
    }

    public void setAsError() {
        isError = true;
    }

    public boolean isError() {
        return isError;
    }

    public JSONObject toJSONObject() {
        JSONObject json = new JSONObject();
        json.put("role", role.toString());
        json.put("content", content);
        if (llm != null) json.put("llm", llm);
        if (inputImages != null && !inputImages.isEmpty()) {
            JSONArray imgArr = new JSONArray();
            for (int i = 0; i < inputImages.size(); i++) {
                imgArr.add(inputImages.get(i));
            }
            json.put("inputImages", imgArr);
        }
        if (outputImage != null && outputImage.length() > 0) {
            json.put("outputImage", outputImage);
        }
        if (toolCalls != null) json.put("toolCalls", toolCalls);
        if (toolCallId != null) json.put("toolCallId", toolCallId);
        if (searchResultCount >= 0) json.put("searchResultCount", searchResultCount);
        json.put("isError", isError);
        return json;
    }

    public static Message fromJSONObject(JSONObject json) {
        String roleStr = json.getNullableString("role");
        Role role = Role.USER;
        if ("assistant".equals(roleStr)) {
            role = Role.ASSISTANT;
        } else if ("system".equals(roleStr)) {
            role = Role.SYSTEM;
        } else if ("tool".equals(roleStr)) {
            role = Role.TOOL;
        }

        String content = json.getNullableString("content");
        if (content == null) content = "";

        String llm = json.getNullableString("llm");

        List<String> inputImages = new ArrayList<String>();
        if (json.has("inputImages")) {
            JSONArray imgArr = json.getNullableArray("inputImages");
            if (imgArr != null) {
                for (int i = 0; i < imgArr.size(); i++) {
                    inputImages.add(imgArr.getString(i));
                }
            }
        }

        Message message = new Message(role, content, inputImages, llm);
        if (json.has("outputImage")) {
            message.setOutputImage(json.getNullableString("outputImage"));
        }
        if (json.has("toolCalls")) {
            message.setToolCalls(json.getNullableArray("toolCalls"));
        } else if (json.has("tool_calls")) {
            message.setToolCalls(json.getNullableArray("tool_calls"));
        }

        if (json.has("toolCallId")) {
            message.setToolCallId(json.getNullableString("toolCallId"));
        } else if (json.has("tool_call_id")) {
            message.setToolCallId(json.getNullableString("tool_call_id"));
        }

        if (json.has("searchResultCount")) {
            message.setSearchResultCount(json.getInt("searchResultCount", -1));
        }
        if (json.getBoolean("isError", false)) {
            message.setAsError();
        }
        return message;
    }
}
